"""Default thermocouple dashboard configuration values."""

DEVICE_NAME = "MCC E-TC-001"
DEFAULT_FURNACE_NUMBER = 1
DEVICE_IP = "192.168.10.101"

DEFAULT_SETPOINT = 75.0
DEFAULT_LOWER_BOUND = 70.0
DEFAULT_UPPER_BOUND = 80.0
DEFAULT_Y_MIN = 60
DEFAULT_Y_MAX = 90

DEFAULT_SAMPLING_FREQUENCY = 1
GRAPH_WINDOW_SECONDS = 300

DEFAULT_OUTPUT_DIRECTORY = "./recordings"
LABVIEW_OUTPUT_CHANNELS = 3

POLLING_INTERVAL = 1000
GRAPH_HEIGHT = 400

CHANNEL_COLORS = {
    1: "#1f77b4",
    2: "#d62728",
    3: "#ff00ff",
}

SETPOINT_COLOR = "red"
LOWER_BOUND_COLOR = "orange"
UPPER_BOUND_COLOR = "purple"
